package scan

import (
	"strings"
	"testing"
)

var (
	testHTMLtype1 = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Gallery</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Gallery" />
	<meta name="description" content="Gallery" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body background="Backround1.gif">
<body style="background-color:#000000">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data/images/picture_1280_001.jpg" alt="Picture_1280_001" title="Picture_1280_001" id="wows1_0"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="data/images/picture_1280_001.jpg" title="Picture_1280_001"><img src="data/tooltips/picture_1280_001.jpg" alt="Picture_1280_001"/>1</a>
<a href="data/images/picture_1280_002.jpg" title="Picture_1280_002">2</a>
<a href="data/images/picture_1280_003.jpg" title="Picture_1280_003">3</a>
<a href="data/images/picture_1280_004.jpg" title="Picture_1280_004">4</a>
<a href="data/images/picture_1280_005.jpg" title="Picture_1280_005">5</a>
<a href="data/images/picture_1280_006.jpg" title="Picture_1280_006">6</a>
<a href="data/images/picture_1280_007.jpg" title="Picture_1280_007">7</a>
<a href="data/images/picture_1280_008.jpg" title="Picture_1280_008">8</a>
<a href="data/images/picture_1280_009.jpg" title="Picture_1280_009">9</a>
<a href="data/images/picture_1280_010.jpg" title="Picture_1280_010">10</a>
</div></div>
<a href="/home">home</a>
<a href="other.png">PNG</a>
<!-- Generated by WOWSlider.com v5.5 -->
	<a href="#" class="ws_frame"></a>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>
`
	testHTMLtype2 = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Gallery</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Gallery" />
	<!-- Start WOWSlider.com HEAD section --> 
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#280000">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/picture001.jpg" alt="Picture-001" title="Picture-001" id="wows1_0"/></li>
<li><img src="data1/images/picture002.jpg" alt="Picture-002" title="Picture-002" id="wows1_1"/></li>
<li><img src="data1/images/picture003.jpg" alt="Picture-003" title="Picture-003" id="wows1_2"/></li>
<li><img src="data1/images/picture004.jpg" alt="Picture-004" title="Picture-004" id="wows1_3"/></li>
<li><img src="data1/images/picture005.jpg" alt="Picture-005" title="Picture-005" id="wows1_4"/></li>
<li><img src="data1/images/picture006.jpg" alt="Picture-006" title="Picture-006" id="wows1_5"/></li>
<li><img src="data1/images/picture007.jpg" alt="Picture-007" title="Picture-007" id="wows1_6"/></li>
<li><img src="data1/images/picture008.jpg" alt="Picture-008" title="Picture-008" id="wows1_7"/></li>
<li><img src="data1/images/picture009.jpg" alt="Picture-009" title="Picture-009" id="wows1_8"/></li>
<li><img src="data1/images/picture010.jpg" alt="Picture-010" title="Picture-010" id="wows1_9"/></li>
</ul></div>
<div class="ws_thumbs">
<div>
<a href="#" title="Picture-001"><img src="data1/tooltips/picture001.jpg" alt="" /></a>
<a href="#" title="Picture-002"><img src="data1/tooltips/picture002.jpg" alt="" /></a>
<a href="#" title="Picture-003"><img src="data1/tooltips/picture003.jpg" alt="" /></a>
<a href="#" title="Picture-004"><img src="data1/tooltips/picture004.jpg" alt="" /></a>
<a href="#" title="Picture-005"><img src="data1/tooltips/picture005.jpg" alt="" /></a>
<a href="#" title="Picture-006"><img src="data1/tooltips/picture006.jpg" alt="" /></a>
<a href="#" title="Picture-007"><img src="data1/tooltips/picture007.jpg" alt="" /></a>
<a href="#" title="Picture-008"><img src="data1/tooltips/picture008.jpg" alt="" /></a>
<a href="#" title="Picture-009"><img src="data1/tooltips/picture009.jpg" alt="" /></a>
<a href="#" title="Picture-010"><img src="data1/tooltips/picture010.jpg" alt="" /></a>
</div>
</div>
<!-- Generated by WOWSlider.com v5.6 -->
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>`
)

func TestLoadGalleryAnchorHREF(t *testing.T) {
	pictures, err := GalleryAnchorHREF(strings.NewReader(testHTMLtype1))
	if err != nil {
		t.Fatalf("GalleryAnchorHREF returned an error: %v", err)
	}

	if len(pictures) != 10 {
		t.Errorf("%d pictures should have been detected, but found %d", 10, len(pictures))
	}
}

func TestEmptyGalleryAnchorHREF(t *testing.T) {

	pictures, err := GalleryAnchorHREF(strings.NewReader(testHTMLtype2))
	if err != nil {
		t.Fatalf("GalleryAnchorHREF returned an error: %v", err)
	}

	if pictures == nil {
		t.Fatalf("GalleryAnchorHREF returned nil")
	}

	if len(pictures) != 0 {
		t.Fatal("no picture should have been detected")
	}
}

func TestLoadGalleryListItem(t *testing.T) {

	pictures, err := GalleryListItem(strings.NewReader(testHTMLtype2))
	if err != nil {
		t.Fatalf("GalleryListItem returned an error: %v", err)
	}

	if pictures == nil {
		t.Fatalf("GalleryListItem returned nil")
	}

	if len(pictures) != 10 {
		t.Errorf("%d pictures should have been detected, but found %d", 10, len(pictures))
	}
}
